title: "Liad's Lil Portfolio"
description: "Data & product projects: SQL, Snowflake, Databricks, Tableau, and more."
author: "Liad Mizrachi"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
