# _config.yml
title: "My Personal Project Portfolio"
description: "My take on quick, yet meaningful wins"
url: "https://findliad.github.io"
baseurl: ""   # user site -> keep empty
author: "Liad Mizrachi"
