title: "Top UK YouTubers 2024"
description: "A data storytelling project analyzing UK YouTubers using Azure Data Studio SQL, Python, and Tableau."
author: "Liad Mizrachi"
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 

